version: '3.5'

networks:
  receipt-net:
    driver: bridge

services:

  localstack: 
    image: localstack/localstack-pro
    container_name: localstack-container
    env_file:
      - .env
    environment:
      - SERVICES=ssm,iam,serverless,s3,lambda,apigateway,cloudformation,sts,cloudwatch, dynamodb,sqs,sns,logs
      - DEBUG=1
      - EDGE_PORT=4566
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN}
      - LAMBDA_EXECUTOR=docker
      - ACTIVATE_PRO=0
      - DOCKER_HOST=unix:///var/run/docker.sock
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=000000000000
      - AWS_SECRET_ACCESS_KEY=12345
    ports:
      - "127.0.0.1:4566:4566"            # LocalStack Gateway
      - "127.0.0.1:4510-4559:4510-4559"  # external services port range
    networks: 
      - receipt-net
    volumes:
      - "${TMPDIR:-/tmp/localstack/}:/var/lib/localstack/"
      - "/var/run/docker.sock:/var/run/docker.sock"


  
  swagger-ui:
    image: swaggerapi/swagger-ui
    container_name: swagger-ui-container
    ports:
      - "80:8080"
    networks: 
      - receipt-net
    volumes:
      - ./design/api-def.yaml://usr/share/nginx/html/api/api-def.yaml
    environment:
      URLS: "[{ url: \"api/api-def.yaml\", name: \"receipt API definitions\" }]" 